typography_spectrum: 0.42314
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37955
analytics:
  google: null
  facebook: null
  twitter: null
name: Marlene Wolfmair
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Projects
purpose: []
